[package]
name = "puzzles_to_study"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version = "0.12.8", features = ["blocking"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }